"""updated card  tables

Revision ID: 38cc3abf7fe0
Revises: ae83a2bc6ce8
Create Date: 2026-04-06 10:06:35.875441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38cc3abf7fe0'
down_revision: Union[str, Sequence[str], None] = 'ae83a2bc6ce8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cards_column_id_fkey'), 'cards', type_='foreignkey')
    op.create_foreign_key(None, 'cards', 'columns', ['column_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.create_foreign_key(op.f('cards_column_id_fkey'), 'cards', 'columns', ['column_id'], ['id'])
    # ### end Alembic commands ###
